In [1]:
import pandas as pd
import numpy as np
from sklearn import metrics
from mlxtend.evaluate import confusion_matrix

In [2]:
data = pd.read_csv('dermatology.data',header=None)
data[33] = pd.to_numeric(data[33], errors='coerce').fillna(0).astype(int)
data[33] = data[33].replace(to_replace=0,value=int(data[33].mean()))

In [3]:
#SPLITING THE DATASET
X = data.iloc[:, 0:34].values
Y = data.iloc[:,34].values
print(X,Y)

[[ 2  2  0 ...  1  0 55]
 [ 3  3  3 ...  1  0  8]
 [ 2  1  2 ...  2  3 26]
 ...
 [ 3  2  2 ...  2  3 28]
 [ 2  1  3 ...  2  3 50]
 [ 3  2  2 ...  3  0 35]] [2 1 3 1 3 2 5 3 4 4 1 2 2 1 3 4 2 1 3 5 6 2 5 3 5 1 6 5 2 3 1 2 1 1 4 2 3
 2 3 1 2 4 1 2 5 3 4 6 2 3 3 4 1 1 5 1 2 3 4 2 6 1 5 1 2 3 1 4 5 1 2 6 3 5
 4 2 2 1 3 5 1 2 2 2 5 1 1 3 1 4 2 2 5 1 3 4 2 5 1 6 2 5 1 2 2 1 4 1 3 1 1
 3 5 3 3 5 2 3 4 1 2 5 6 1 1 2 6 3 5 4 1 1 3 5 5 1 4 2 3 1 2 1 1 3 3 3 2 5
 4 2 2 1 1 1 5 3 2 3 2 2 4 2 3 6 2 1 1 3 4 3 3 1 1 1 3 1 1 2 3 3 1 1 1 1 6
 2 2 2 2 1 3 3 3 1 1 2 3 2 2 2 5 5 5 5 5 1 1 1 1 1 1 1 3 3 3 3 3 3 4 4 4 4
 5 5 5 5 5 5 5 2 2 2 2 1 1 1 1 1 1 6 6 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 4 4 4
 4 4 4 5 5 5 5 6 6 6 4 4 4 1 1 1 1 1 2 2 4 4 4 1 1 2 2 2 3 3 3 3 1 1 1 1 5
 5 5 5 5 3 3 3 4 1 1 4 4 4 1 1 1 3 3 3 3 3 1 1 1 1 4 4 1 1 4 3 3 4 1 1 4 4
 5 5 1 1 5 5 3 1 5 5 6 6 4 4 6 6 6 1 1 1 5 5 1 1 1 1 2 2 4 4 3 3 1]


In [4]:
#SPILITTING THE DATA
from sklearn.model_selection import train_test_split
X_train , X_test, Y_train , Y_test = train_test_split(X , Y , test_size = 0.3)

In [5]:
#LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
var = LogisticRegression(solver='newton-cg',multi_class='multinomial')
var.fit(X_train, Y_train)
Y_pred = var.predict(X_test)
print("Accuracy:",metrics.accuracy_score(Y_pred, Y_test))

Accuracy: 0.9454545454545454


In [6]:
#Confusion matrix
cm = confusion_matrix(Y_test, Y_pred, binary = False)
cm

array([[33,  0,  0,  0,  0,  0],
       [ 0, 13,  0,  2,  0,  0],
       [ 0,  0, 19,  0,  0,  0],
       [ 0,  4,  0, 11,  0,  0],
       [ 0,  0,  0,  0, 17,  0],
       [ 0,  0,  0,  0,  0, 11]])

In [7]:
#DECISION TREE

#from sklearn.learn import DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
var = DecisionTreeClassifier()
var.fit(X_train, Y_train)
Y_pred = var.predict(X_test)
print("Accuracy:",metrics.accuracy_score(Y_pred, Y_test))



Accuracy: 0.9636363636363636


In [8]:
#SVM
from sklearn import svm 
var = svm.SVC(kernel='linear')
var.fit(X_train, Y_train)
Y_pred = var.predict(X_test)
print("Accuracy:",metrics.accuracy_score(Y_pred, Y_test))

Accuracy: 0.9454545454545454


In [9]:
#RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, bootstrap=True)
rf.fit(X_train,Y_train)
Y_pred = rf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))

Accuracy: 0.9636363636363636
